name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build and publish mobius-config
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn
      - run: yarn build
      - run: |
          echo 'npmAuthToken: "${NPM_AUTH_TOKEN}"' >> .yarnrc.yml
          cat .yarnrc.yml
      - name: Publish
        run: yarn npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
